name: 'Report OPEN Issues'
description: 'Report issues that are OPEN to Ryver chat, based on provided labels'
branding:
  icon: 'calendar'
  color: 'white'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  repoToken:
    description: 'github token'
    required: true
    default: '${{ github.token }}'
  repository:
    description: 'the repository name'
    required: true
    default: '${{ github.repository }}'
  repositoryOwner:
    description: 'the repository owner'
    required: true
    default: '${{ github.repository_owner }}'
  company:
    description: 'Company that will receive the notification'
    required: true
    default: 'RandomCompany'
  rvrToken:
    description: 'Bots Token'
    required: true
    default: 'randomRVR'
  room:
    description: 'Number for the room that will receive the notification'
    required: true
    default: 'otherRoom'
