name: 'Report OPEN Issues'
description: 'Report issues that are OPEN to Ryver chat, based on provided labels'
inputs:
  company:
    description: 'Company that will receive the notification'
    required: true
    default: 'RandomCompany'
  rvrToken:
    required: true
    default: 'randomRVR'
  room:
    required: true
    default: 'otherRoom'
  gh_token:
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
