name: 'Trigger Issues check'

on:
# When it works properly, we can setup the schedule
#   schedule:
#     - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Check open issues based on labels
      uses: RicardoPoleo/MonitorIssues@main
